version: "3.3"
services:
  cfn:
    build: .
    image: cloudformation-z:node8
    volumes:
      - ~/.aws:/root/.aws
      - ./cfn:/workspace
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - NODE_ENV=${NODE_ENV}
