service: ${self:custom.system}

custom:
  system: "SampleSystem"
  stage: ${opt:stage, self:provider.stage}
  config:
    DEV:
      authed_role_name: ${self:custom.system}-${self:custom.stage}-Authenticated

plugins:
  - serverless-offline

package:
  exclude:
    - cfn/**

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  timeout: 10
  stage: DEV
  region: ap-northeast-1
  stackTags:
    System: ${self:custom.system}
    Stage: ${self:custom.stage}
  environment:
    NODE_ENV: ${self:custom.stage}
    DEBUG: "${self:custom.system}:*"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cognito-identity:GetOpenIdTokenForDeveloperIdentity"
      Resource: "*"

functions:
  Hello:
    handler: src/handler/hello.handler
    events:
      - http:
          method: GET
          path: hello
          authorizer: aws_iam
          cors: true

resources:
  Resources:
    AuthedPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: "invokable-authed-backend-api"
        Roles:
          - ${self:custom.config.${self:custom.stage}.authed_role_name}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "execute-api:Invoke"
              Resource:
                "Fn::Join": ["", ["arn:aws:execute-api:ap-northeast-1:", {Ref: "AWS::AccountId"}, ":", {Ref: ApiGatewayRestApi}, "/${self:custom.stage}/*"]]
