version: "3"
services:
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    ports:
      - 3306:3306
    restart: always
  app:
    image: python-sqlalchemy-sample
    build: .
    links:
      - db:db.local
    volumes:
      - .:/work
    working_dir: /work
