service:
  name: ecma-practice

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  system: "EcmaPractice"
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs6.10
  stage: DEV
  region: ap-northeast-1

functions:
  GetUsers:
    handler: handlers/route/users.get
    events:
      - http:
          method: get
          path: users
  PostUsers:
    handler: handlers/route/users.post
    events:
      - http:
          method: post
          path: users
