version: "3.3"
services:
  circus:
    build: .
    image: circus
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - 8080:8080
      - 9999:9999
    command: circusd /workspace/circus.ini
