service: sls-express

provider:
  name: aws
  runtime: nodejs6.10
  stage: DEV
  region: ap-northeast-1

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
  healthcheck:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /hc
