import { GetServerSideProps } from "next";
import Head from "next/head";
// import useSWR from "swr"

interface Pokemon {
  name: string;
  url: string;
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  console.log("Index: getServerSideProps");
  const response = await fetch("https://pokeapi.co/api/v2/pokemon");
  const data = await response.json();
  const pokemon = data.results as Pokemon[];
  return {
    props: { pokemon },
  };
};

export default function Home(props: { pokemon: Pokemon[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-10">
        <h1 className="text-5xl font-bold">Hello SSR</h1>
        <ul>
          {props.pokemon.map((p) => {
            return <li key={p.url}>{p.name}</li>;
          })}
        </ul>
      </main>
    </>
  );
}
